"""
DynamoDB operations for device management.

Schema:
- Device registry: pk=DEVICE#{device_id}, sk=META
- Phone-device link: pk=PHONE#{phone}, sk=DEVICE#{device_id}
"""

from datetime import datetime
from typing import Any

from .db import get_dynamodb_table


# =============================================================================
# Device Registry Operations
# =============================================================================


def register_device(
    device_id: str,
    fcm_token: str,
    platform: str,
    invitation_code: str,
    phone_number: str | None = None,
) -> None:
    """
    Register a new device for push notifications.

    Args:
        device_id: Unique device identifier (UUID generated by app)
        fcm_token: Firebase Cloud Messaging token
        platform: Device platform ('android', 'ios', 'web')
        invitation_code: The invitation code used to register
        phone_number: Optional phone number to link to this device
    """
    table = get_dynamodb_table()
    now = datetime.utcnow().isoformat() + "Z"

    item: dict[str, Any] = {
        "pk": f"DEVICE#{device_id}",
        "sk": "META",
        "device_id": device_id,
        "fcm_token": fcm_token,
        "platform": platform,
        "invitation_code_used": invitation_code,
        "created_at": now,
        "updated_at": now,
    }

    if phone_number:
        item["phone_number"] = phone_number

    table.put_item(Item=item)

    # If phone number is provided, create the phone-device link
    if phone_number:
        link_device_to_phone(phone_number, device_id)


def get_device(device_id: str) -> dict[str, Any] | None:
    """
    Get a device record by device ID.

    Returns:
        Device record or None if not found
    """
    table = get_dynamodb_table()

    response = table.get_item(Key={"pk": f"DEVICE#{device_id}", "sk": "META"})

    return response.get("Item")


def is_device_registered(device_id: str) -> bool:
    """Check if a device is already registered."""
    return get_device(device_id) is not None


def update_fcm_token(device_id: str, fcm_token: str) -> bool:
    """
    Update the FCM token for a device.

    Args:
        device_id: Device identifier
        fcm_token: New FCM token

    Returns:
        True if updated, False if device not found
    """
    table = get_dynamodb_table()

    try:
        table.update_item(
            Key={"pk": f"DEVICE#{device_id}", "sk": "META"},
            UpdateExpression="SET fcm_token = :token, updated_at = :updated",
            ExpressionAttributeValues={
                ":token": fcm_token,
                ":updated": datetime.utcnow().isoformat() + "Z",
            },
            ConditionExpression="attribute_exists(pk)",
        )
        return True
    except table.meta.client.exceptions.ConditionalCheckFailedException:
        return False


def delete_device(device_id: str) -> bool:
    """
    Delete a device registration.

    Returns:
        True if deleted, False if not found
    """
    table = get_dynamodb_table()

    # First get the device to check if it has a linked phone
    device = get_device(device_id)
    if not device:
        return False

    # Delete the device record
    response = table.delete_item(
        Key={"pk": f"DEVICE#{device_id}", "sk": "META"},
        ReturnValues="ALL_OLD",
    )

    # If device had a linked phone, remove the link
    phone_number = device.get("phone_number")
    if phone_number:
        unlink_device_from_phone(phone_number, device_id)

    return "Attributes" in response


# =============================================================================
# Phone-Device Link Operations
# =============================================================================


def link_device_to_phone(phone_number: str, device_id: str) -> None:
    """
    Create a link between a phone number and a device.

    This allows looking up all devices for a phone number.

    Args:
        phone_number: Phone number in E.164 format
        device_id: Device identifier
    """
    table = get_dynamodb_table()

    table.put_item(
        Item={
            "pk": f"PHONE#{phone_number}",
            "sk": f"DEVICE#{device_id}",
            "phone_number": phone_number,
            "device_id": device_id,
            "linked_at": datetime.utcnow().isoformat() + "Z",
        }
    )

    # Also update the device record with the phone number
    table.update_item(
        Key={"pk": f"DEVICE#{device_id}", "sk": "META"},
        UpdateExpression="SET phone_number = :phone, updated_at = :updated",
        ExpressionAttributeValues={
            ":phone": phone_number,
            ":updated": datetime.utcnow().isoformat() + "Z",
        },
    )


def unlink_device_from_phone(phone_number: str, device_id: str) -> bool:
    """
    Remove the link between a phone number and a device.

    Returns:
        True if unlinked, False if link not found
    """
    table = get_dynamodb_table()

    response = table.delete_item(
        Key={"pk": f"PHONE#{phone_number}", "sk": f"DEVICE#{device_id}"},
        ReturnValues="ALL_OLD",
    )

    return "Attributes" in response


def get_devices_for_phone(phone_number: str) -> list[dict[str, Any]]:
    """
    Get all devices linked to a phone number.

    Returns:
        List of device records
    """
    from boto3.dynamodb.conditions import Key

    table = get_dynamodb_table()

    # Query for all device links under this phone
    response = table.query(
        KeyConditionExpression=Key("pk").eq(f"PHONE#{phone_number}")
        & Key("sk").begins_with("DEVICE#"),
    )

    device_links = response.get("Items", [])

    # Fetch the full device records
    devices = []
    for link in device_links:
        device = get_device(link["device_id"])
        if device:
            devices.append(device)

    return devices


# =============================================================================
# Device Subscription Operations
# =============================================================================


def add_device_subscription(
    device_id: str,
    resort_name: str,
    target_date: str,
    unsubscribe_token: str,
    notification_type: str = "push",
) -> None:
    """
    Add a subscription for a device.

    Args:
        device_id: Device identifier
        resort_name: Name of the resort
        target_date: Date to track (YYYY-MM-DD format)
        unsubscribe_token: Token for unsubscribing from this specific alert
        notification_type: Type of notification ('push', 'sms', 'both')
    """
    table = get_dynamodb_table()

    table.put_item(
        Item={
            "pk": f"DATE#{target_date}",
            "sk": f"RESORT#{resort_name}#DEVICE#{device_id}",
            "device_id": device_id,
            "resort_name": resort_name,
            "date": target_date,
            "unsubscribe_token": unsubscribe_token,
            "notification_type": notification_type,
            "last_status": "unknown",
            "created_at": datetime.utcnow().isoformat() + "Z",
        }
    )


def get_device_subscription(
    device_id: str, resort_name: str, target_date: str
) -> dict[str, Any] | None:
    """
    Get a specific subscription for a device.

    Returns:
        Subscription record or None if not found
    """
    table = get_dynamodb_table()

    response = table.get_item(
        Key={
            "pk": f"DATE#{target_date}",
            "sk": f"RESORT#{resort_name}#DEVICE#{device_id}",
        }
    )

    return response.get("Item")


def remove_device_subscription(
    device_id: str, resort_name: str, target_date: str
) -> bool:
    """
    Remove a subscription for a device.

    Returns:
        True if deleted, False if not found
    """
    table = get_dynamodb_table()

    response = table.delete_item(
        Key={
            "pk": f"DATE#{target_date}",
            "sk": f"RESORT#{resort_name}#DEVICE#{device_id}",
        },
        ReturnValues="ALL_OLD",
    )

    return "Attributes" in response


def get_subscriptions_by_device(device_id: str) -> list[dict[str, Any]]:
    """
    Get all subscriptions for a device.

    Returns:
        List of subscription records
    """
    from boto3.dynamodb.conditions import Attr

    table = get_dynamodb_table()
    today = datetime.now().strftime("%Y-%m-%d")

    # Scan for device subscriptions with dates >= today
    response = table.scan(
        FilterExpression=Attr("date").gte(today)
        & Attr("sk").begins_with("RESORT#")
        & Attr("device_id").eq(device_id)
    )

    return response.get("Items", [])


def remove_all_device_subscriptions(device_id: str) -> int:
    """
    Remove all subscriptions for a device.

    Returns:
        Number of subscriptions removed
    """
    subscriptions = get_subscriptions_by_device(device_id)
    table = get_dynamodb_table()

    for sub in subscriptions:
        table.delete_item(Key={"pk": sub["pk"], "sk": sub["sk"]})

    return len(subscriptions)
